### ISSUE TITLE
Latest release fails to build

### ISSUE THREAD

**Issue by simlu** [chjj/n64#8]
Running on Amazon Linux, latest release [0.1.1](https://github.com/chjj/n64/releases/tag/v0.1.1) started failing with the following error message:

```
gyp: binding.gyp not found (cwd: /project/node_modules/n64) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v6.11.5/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.4.0-112-generic
gyp ERR! command "/root/.nvm/versions/node/v6.11.5/bin/node" "/root/.nvm/versions/node/v6.11.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /project/node_modules/n64
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/root/.nvm/versions/node/v6.11.5/bin/node" "/root/.nvm/versions/node/v6.11.5/bin/npm" "install"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! n64@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the n64@0.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the n64 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs n64
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls n64
npm ERR! There is likely additional logging output above.
```

**Comment by chjj** [comment]
Ugh, this is because npm automatically tries to build anything with a binding.gyp in it, and I accidentally pushed the binding.gyp to npm. =/ Will fix.

**Comment by simlu** [comment]
Sweet, thank you!
